# 配置服务器端口号和项目应用路径
#系统分为管理员和客户两种角色。
#管理员：客户管理（增删改查）、消费记录管理（增删改查）、统计报表。
#客户：查看消费记录。
server:
  port: 8888

  servlet:
    context-path: /crm

# 自定义数据
web:
  upload-path: D:/image

# 配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/member?serverTimezone=GMT%2B8
    username: root
    password: root12
  messages:
    basename: il8n/messages #相对路径 开头请勿添加斜杠
    encoding: UTF-8

  mvc:
    static-path-pattern: /**

  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}

  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
    prefix: classpath:/templates/

logging:
  level:
    com.gem.mapper: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #使用驼峰法映射属性,配置这个resultType可以映射
    map-underscore-to-camel-case: true
  #MyBatis Mapper 所对应的 XML 文件位置
  mapper-locations: classpath*:mapper/*.xml

